### ISSUE TITLE
Login with facebook in production with cordova app

### ISSUE THREAD

**Issue by royipressburger** [ronzeidman/ng2-ui-auth#52]
Hi

Im trying to create a login with facebook, with my ionic app.
The thing is that everything is working good when I test it on the browser.
But when im running it on a device im having some issues with the redirect URL.
1. I have no idea what to write there.
2. If I write something I do not get redirect to back to the application.

I have tried to put `https://www.facebook.com/connect/login_success.html` as a redirect url. both in the application and in facebook console.
the thing is that I do not get redirect back the application thus in my login screen.

Any idea?

**Comment by royipressburger** [comment]
Ok so i found a way to get this done. To anyone else that have this issue:
1. Make sure you redirect url us `http://localhost/` NOTE that the `/` at the end is mandatory

2. Extend the auth config class and add ` cordova = true;`

3. Install cordova-inappbrowser
4. Make sure that on Facebook console you add the url http://localhost/

@ronziedman, maybe the `cordova` variable should get its value dynamiclly? So we wont need to chanes the config over and over again when switching between dev and prod environments?

**Comment by ronzeidman** [comment]
Will defaulting `cordova = document.URL.indexOf( 'http' ) === -1` work?

**Comment by royipressburger** [comment]
No sure to be honest.. I see that in `satellizer` he just uses `window.cordova`
Ill test that later today and let you know

**Comment by royipressburger** [comment]
@ronzeidman  `window.cordova` will do just fine I think
When running on browser I got undefined, and on emulator I got some data in it

**Comment by ronzeidman** [comment]
You can try using the master branch now, since this is a non invasive fix when you tell me it works for you I'll publish it to npm.
Thanks

**Comment by ronzeidman** [comment]
fixed in 4.1.1

**Comment by royipressburger** [comment]
@ronzeidman Hi again.. sorry I wasn't here to test that. 4.1.1 has been released? cant see it on the releases tab

**Comment by ronzeidman** [comment]
Yes, https://www.npmjs.com/package/ng2-ui-auth

**Comment by dbpeterson2** [comment]
Hi there, I've read through this entire thread and I'm still not able to get my iPhone to redirect correctly after entering facebook username and password. I'm using version 6.0.0. and setting the redirectUri: 'http://localhost/'. What am I missing?

**Comment by dbpeterson2** [comment]
Scratch that...didn't have cordova-inappbrowser installed.
